robot_id: go2_with_feet
source_xml: assets/robots/go2_with_feet/go2_with_feet.xml
fk_xml: assets/fk/go2_with_feet_fk.xml
njoints: 12
nbodies: 17

# joint_index_reference:
#   [0] FR_hip_joint
#   [1] FR_thigh_joint
#   [2] FR_calf_joint
#   [3] FL_hip_joint
#   [4] FL_thigh_joint
#   [5] FL_calf_joint
#   [6] RR_hip_joint
#   [7] RR_thigh_joint
#   [8] RR_calf_joint
#   [9] RL_hip_joint
#   [10] RL_thigh_joint
#   [11] RL_calf_joint
# body_index_reference:
#   [0] base
#   [1] FR_hip
#   [2] FR_thigh
#   [3] FR_calf
#   [4] FR_foot
#   [5] FL_hip
#   [6] FL_thigh
#   [7] FL_calf
#   [8] FL_foot
#   [9] RR_hip
#   [10] RR_thigh
#   [11] RR_calf
#   [12] RR_foot
#   [13] RL_hip
#   [14] RL_thigh
#   [15] RL_calf
#   [16] RL_foot
joint_limits:
  lower: [-1.0472, -1.5708, -2.7227, -1.0472, -1.5708, -2.7227, -1.0472, -0.5236,
    -2.7227, -1.0472, -0.5236, -2.7227]
  upper: [1.0472, 3.4907, -0.83776, 1.0472, 3.4907, -0.83776, 1.0472, 4.5379, -0.83776,
    1.0472, 4.5379, -0.83776]
  source: xml_effective_range
base_body: base
