robot_id: go2_with_d1
source_xml: assets/robots/go2_with_d1/go2_with_d1.xml
fk_xml: assets/fk/go2_with_d1_fk.xml
njoints: 20
nbodies: 26

# joint_index_reference:
#   [0] FL_hip_joint
#   [1] FL_thigh_joint
#   [2] FL_calf_joint
#   [3] FR_hip_joint
#   [4] FR_thigh_joint
#   [5] FR_calf_joint
#   [6] RL_hip_joint
#   [7] RL_thigh_joint
#   [8] RL_calf_joint
#   [9] RR_hip_joint
#   [10] RR_thigh_joint
#   [11] RR_calf_joint
#   [12] arm_1_joint
#   [13] arm_2_joint
#   [14] arm_3_joint
#   [15] arm_4_joint
#   [16] arm_5_joint
#   [17] arm_6_joint
#   [18] arm_7_1_joint
#   [19] arm_7_2_joint
# body_index_reference:
#   [0] base_link
#   [1] FL_hip
#   [2] FL_thigh
#   [3] FL_calf
#   [4] FL_foot
#   [5] FR_hip
#   [6] FR_thigh
#   [7] FR_calf
#   [8] FR_foot
#   [9] RL_hip
#   [10] RL_thigh
#   [11] RL_calf
#   [12] RL_foot
#   [13] RR_hip
#   [14] RR_thigh
#   [15] RR_calf
#   [16] RR_foot
#   [17] d1_base_link
#   [18] d1_link1
#   [19] d1_link2
#   [20] d1_link3
#   [21] d1_link4
#   [22] d1_link5
#   [23] d1_link6
#   [24] d1_gripper_1
#   [25] d1_gripper_2
nominal_base_height: 0.445
joint_limits:
  lower: [-1.0472, -1.5708, -2.7227, -1.0472, -1.5708, -2.7227, -1.0472, -0.5236,
    -2.7227, -1.0472, -0.5236, -2.7227, -2.36, -1.57, -1.57, -2.36, -1.57, -2.36,
    0.0, -0.033]
  upper: [1.0472, 3.4907, -0.83776, 1.0472, 3.4907, -0.83776, 1.0472, 4.5379, -0.83776,
    1.0472, 4.5379, -0.83776, 2.36, 1.57, 1.57, 2.36, 1.57, 2.36, 0.033, 0.0]
  source: xml_effective_range
base_body: base_link
