pair_id: g1_to_go2_with_d1
task_family: manipulation
src_robot: g1
dst_robot: go2_with_d1
correspondence:
  body_groups:
  - name: legs_all
    src_body_indices: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15]
    dst_body_indices: [1, 2, 3, 4, 9, 10, 11, 12, 5, 6, 7, 8, 13, 14, 15, 16]
  - name: right arm
    src_body_indices: [30, 31, 32, 33, 34, 35, 36, 37]
    dst_body_indices: [17, 18, 19, 20, 21, 22, 23, 24, 25]
  joint_groups:
  - name: legs_all
    src_joint_indices: [0, 1, 2, 3, 6, 7, 8, 9]
    dst_joint_indices: [0, 1, 2, 6, 7, 8, 3, 4, 5, 9, 10, 11]
  - name: right arm
    src_joint_indices: [22, 23, 24, 25, 26, 27, 28]
    dst_joint_indices: [12, 13, 14, 15, 16, 17, 18, 19]
loss_overrides: 
  lambda_skating: 50.0
  lambda_grounding: 100.0
  lambda_ee: 0.1
  lambda_cycle: 0.5
  lambda_cycle_motion: 10.0
  physics_ground_mode: zero_nominal
  ee_match_mode: disp
  ee_norm_mode: none
  lambda_retar_vel: 100.0
indices:
  src_feet: [7, 15]
  dst_feet: [4, 8, 12, 16]
  src_ee: [37]
  dst_ee: [25]
